project_name: go-exploitdb
release:
  github:
    owner: vulsio
    name: go-exploitdb
builds:
- id: linux-amd64
  goos:
  - linux
  goarch:
  - amd64
  main: .
  ldflags: -s -w -X github.com/vulsio/go-exploitdb/config.Version={{.Version}} -X github.com/vulsio/go-exploitdb/config.Revision={{.Commit}}
  binary: go-exploitdb
- id: linux-arm64
  goos:
  - linux
  goarch:
  - arm64
  main: .
  ldflags: -s -w -X github.com/vulsio/go-exploitdb/config.Version={{.Version}} -X github.com/vulsio/go-exploitdb/config.Revision={{.Commit}}
  binary: go-exploitdb
archives:
- name_template: '{{ .Binary }}_{{.Version}}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  format: tar.gz
  files:
  - LICENSE
  - README*
snapshot:
  name_template: SNAPSHOT-{{ .Commit }}
